adb shell pm uninstall -k --user 0 com.facebook.katana
adb shell pm uninstall -k --user 0 com.mcafee.vsm_android_sbm
adb shell pm uninstall -k --user 0 com.mobiroo.xgen
adb shell pm uninstall -k --user 0 com.netflix.mediaclient
adb shell pm uninstall -k --user 0 jp.co.bbss.android.security.sagiwall_softbank
adb shell pm uninstall -k --user 0 jp.co.optim.orujff00
adb shell pm uninstall -k --user 0 jp.co.softbank.livr
adb shell pm uninstall -k --user 0 jp.co.softbank.OfficialApp
adb shell pm uninstall -k --user 0 jp.co.softbank.wispr.froyo
adb shell pm uninstall -k --user 0 jp.co.yahoo.android.ebookjapan.preinstall
adb shell pm uninstall -k --user 0 jp.co.yahoo.android.paypayfleamarket
adb shell pm uninstall -k --user 0 jp.co.yahoo.android.pmall
adb shell pm uninstall -k --user 0 jp.co.yahoo.android.sports.sportsnavi
adb shell pm uninstall -k --user 0 jp.co.yahoo.android.ybackup
adb shell pm uninstall -k --user 0 jp.co.yahoo.android.yjtop
adb shell pm uninstall -k --user 0 jp.co.yahoo.android.yshopping
adb shell pm uninstall -k --user 0 jp.co.yahoo.gyao.android.app
adb shell pm uninstall -k --user 0 jp.ne.paypay.android.app
adb shell pm uninstall -k --user 0 jp.softbank.beginnerguide
adb shell pm uninstall -k --user 0 jp.softbank.mb.amcn
adb shell pm uninstall -k --user 0 jp.softbank.mb.basketball
adb shell pm uninstall -k --user 0 jp.softbank.mb.bizlock
adb shell pm uninstall -k --user 0 jp.softbank.mb.customersupportweb
adb shell pm uninstall -k --user 0 jp.softbank.mb.datamigration
adb shell pm uninstall -k --user 0 jp.softbank.mb.dmb
adb shell pm uninstall -k --user 0 jp.softbank.mb.fivegservice
adb shell pm uninstall -k --user 0 jp.softbank.mb.ichinaviclt
adb shell pm uninstall -k --user 0 jp.softbank.mb.mimamorimap
adb shell pm uninstall -k --user 0 jp.softbank.mb.mysoftbankweb
adb shell pm uninstall -k --user 0 jp.softbank.mb.parentalcontrols
adb shell pm uninstall -k --user 0 jp.softbank.mb.plusmessage
adb shell pm uninstall -k --user 0 jp.softbank.mb.sbmultiangle
adb shell pm uninstall -k --user 0 jp.softbank.mb.securitypack
adb shell pm uninstall -k --user 0 jp.softbank.mb.survey
adb shell pm uninstall -k --user 0 jp.softbank.meiwakudenwablock
adb shell pm uninstall -k --user 0 jp.viewn.bookhodai.yomihoudaipremium
pause
