adb shell pm uninstall -k --user 0 com.amazon.kindle
adb shell pm uninstall -k --user 0 com.amazon.mShop.android.shopping
adb shell pm uninstall -k --user 0 com.android.contacts
adb shell pm uninstall -k --user 0 com.android.dialer
adb shell pm uninstall -k --user 0 com.facebook.katana
adb shell pm uninstall -k --user 0 com.facebook.orca
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.docs
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.sheets
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.slides
adb shell pm uninstall -k --user 0 com.google.android.apps.tachyon
adb shell pm uninstall -k --user 0 com.google.android.music
adb shell pm uninstall -k --user 0 com.google.android.tts
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.instagram.android
adb shell pm uninstall -k --user 0 com.ipg.gguide.dcm_app.android
adb shell pm uninstall -k --user 0 com.mcafee.vsm_android_dcm
adb shell pm uninstall -k --user 0 com.mobileselect.somcprein
adb shell pm uninstall -k --user 0 com.nttdocomo.android.accountauthenticator
adb shell pm uninstall -k --user 0 com.nttdocomo.android.accountwipe
adb shell pm uninstall -k --user 0 com.nttdocomo.android.anmane2
adb shell pm uninstall -k --user 0 com.nttdocomo.android.apnsw
adb shell pm uninstall -k --user 0 com.nttdocomo.android.applicationmanager
adb shell pm uninstall -k --user 0 com.nttdocomo.android.areamail
adb shell pm uninstall -k --user 0 com.nttdocomo.android.atf
adb shell pm uninstall -k --user 0 com.nttdocomo.android.bugreport
adb shell pm uninstall -k --user 0 com.nttdocomo.android.cloudset
adb shell pm uninstall -k --user 0 com.nttdocomo.android.cloudstorageservice
adb shell pm uninstall -k --user 0 com.nttdocomo.android.databackup
adb shell pm uninstall -k --user 0 com.nttdocomo.android.devicehelp
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dhome
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dmenu2
adb shell pm uninstall -k --user 0 com.nttdocomo.android.docomomail
adb shell pm uninstall -k --user 0 com.nttdocomo.android.docomoset
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dpoint
adb shell pm uninstall -k --user 0 com.nttdocomo.android.iconcier
adb shell pm uninstall -k --user 0 com.nttdocomo.android.iconcier_contents
adb shell pm uninstall -k --user 0 com.nttdocomo.android.idmanager
adb shell pm uninstall -k --user 0 com.nttdocomo.android.initialization
adb shell pm uninstall -k --user 0 com.nttdocomo.android.kittingmanager
adb shell pm uninstall -k --user 0 com.nttdocomo.android.mascot
adb shell pm uninstall -k --user 0 com.nttdocomo.android.mediaplayer
adb shell pm uninstall -k --user 0 com.nttdocomo.android.moneyrecord
adb shell pm uninstall -k --user 0 com.nttdocomo.android.msg
adb shell pm uninstall -k --user 0 com.nttdocomo.android.osv
adb shell pm uninstall -k --user 0 com.nttdocomo.android.pf.dcmippushaggregator
adb shell pm uninstall -k --user 0 com.nttdocomo.android.pf.dcmwappush
adb shell pm uninstall -k --user 0 com.nttdocomo.android.phonemotion
adb shell pm uninstall -k --user 0 com.nttdocomo.android.photocollection
adb shell pm uninstall -k --user 0 com.nttdocomo.android.photoviewer
adb shell pm uninstall -k --user 0 com.nttdocomo.android.schedulememo
adb shell pm uninstall -k --user 0 com.nttdocomo.android.screenlockservice
adb shell pm uninstall -k --user 0 com.nttdocomo.android.sdcardbackup
adb shell pm uninstall -k --user 0 com.nttdocomo.android.store
adb shell pm uninstall -k --user 0 com.nttdocomo.android.tapandpay
adb shell pm uninstall -k --user 0 com.nttdocomo.android.toruca
adb shell pm uninstall -k --user 0 com.nttdocomo.android.voiceeditor
adb shell pm uninstall -k --user 0 com.nttdocomo.android.voicetranslation
adb shell pm uninstall -k --user 0 com.nttdocomo.osaifu.tsmproxy
adb shell pm uninstall -k --user 0 com.rsupport.rs.activity.ntt
adb shell pm uninstall -k --user 0 com.scee.psxandroid
adb shell pm uninstall -k --user 0 com.somc.so04j.manual
adb shell pm uninstall -k --user 0 com.sony.drbd.reader.other.jp
adb shell pm uninstall -k --user 0 com.sony.nfx.app.sfrc
adb shell pm uninstall -k --user 0 com.sony.tvsideview.videoph
adb shell pm uninstall -k --user 0 com.sonyericsson.androidapp.sehome
adb shell pm uninstall -k --user 0 com.sonymobile.androidapp.cameraaddon.areffect
adb shell pm uninstall -k --user 0 com.sonymobile.docomoemoji.license
adb shell pm uninstall -k --user 0 com.sonymobile.email
adb shell pm uninstall -k --user 0 com.sonymobile.entrance
adb shell pm uninstall -k --user 0 com.sonymobile.lifelog
adb shell pm uninstall -k --user 0 com.sonymobile.moviecreator.rmm
adb shell pm uninstall -k --user 0 com.sonymobile.scan3d
adb shell pm uninstall -k --user 0 com.sonymobile.sketch
adb shell pm uninstall -k --user 0 com.touchtype.swiftkey
adb shell pm uninstall -k --user 0 com.twitter.android
adb shell pm uninstall -k --user 0 com.uievolution.gguide.android
adb shell pm uninstall -k --user 0 com.wsandroid.suite
adb shell pm uninstall -k --user 0 jp.co.lawson.activity
adb shell pm uninstall -k --user 0 jp.co.lawson.android
adb shell pm uninstall -k --user 0 jp.co.mcdonalds.android
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.anshinmode
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.bridgelauncher
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.carriermail
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.dbook
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.lcsapp
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.lcsappsub
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.saigaiban
adb shell pm uninstall -k --user 0 jp.co.omronsoft.android.decoemojimanager_docomo
adb shell pm uninstall -k --user 0 jp.dmapnavi.navi02
adb shell pm uninstall -k --user 0 jp.id_credit_sp.android
pause
